import datetime
from pydantic import BaseModel, Field

### IDデータ作成はDBで生成するので、Modelは分けないとエラーになる。IDのモデルに継承する。


## For Create Booking (booking_id will be generated by DB)

class BookingCreate(BaseModel):
    user_id: int
    room_id: int
    booked_num: int
    start_datetime: datetime.datetime
    end_datetime: datetime.datetime

## BookingCreateを継承
class Booking(BookingCreate):
    booking_id: int
   
    class Config:
        orm_mode = True

## For Create User (ID will be generated by DB)
class UserCreate(BaseModel):
    username: str = Field(max_length=20)

## UserCreateを継承
class User(UserCreate):
    user_id: int
    
    class Config:
        orm_mode = True

## For Create Reserve Room
class RoomCreate(BaseModel):
    room_name: str = Field(max_length=20)
    capacity: int

## RoomCreateを継承
class Room(RoomCreate):
    room_id: int
    
    class Config:
        orm_mode = True
